#!/usr/bin/env python3
"""
Gas domain pre-analysis — step 1 research pipeline.

Usage (from repo root):
  python research/run_gas.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# allow imports when run as script
sys.path.insert(0, str(Path(__file__).resolve().parent))

from clean import clean_series
from explore import analyze_pairs, rolling_correlation
from features import build_gas_features
from series_io import load_domain, load_series
from paths import ensure_output
from qa import qa_series


def _md_table(rows: list[dict], cols: list[str]) -> str:
    if not rows:
        return "_no data_\n"
    lines = ["| " + " | ".join(cols) + " |", "| " + " | ".join(["---"] * len(cols)) + " |"]
    for r in rows:
        lines.append("| " + " | ".join(str(r.get(c, "")) for c in cols) + " |")
    return "\n".join(lines) + "\n"


def main() -> int:
    out_dir = ensure_output()
    loaded = load_domain("gas")
    missing = [s for s in ("HUB", "TTF") if s not in loaded]
    if missing:
        print(f"ERROR: required series missing: {missing}", file=sys.stderr)
        return 1

    qa_reports = []
    clean_map: dict = {}
    meta_map: dict = {}

    for sid, (raw, meta) in loaded.items():
        meta_map[sid] = meta
        cleaned = clean_series(raw, meta)
        clean_map[sid] = cleaned
        qa_reports.append(qa_series(cleaned, meta).to_dict())

    hub, hub_meta = clean_map["HUB"], meta_map["HUB"]
    ttf, ttf_meta = clean_map["TTF"], meta_map["TTF"]
    vix = clean_map.get("VIX")
    ngs_raw = None
    if "NGS" in clean_map:
        ngs_raw = clean_map["NGS"]
    else:
        try:
            ngs_raw, ngs_meta = load_series("NGS")
            ngs_raw = clean_series(ngs_raw, ngs_meta)
            meta_map["NGS"] = ngs_meta
        except FileNotFoundError:
            pass

    features = build_gas_features(
        hub, ttf, vix=vix, ngs=ngs_raw,
        hub_meta=hub_meta, ttf_meta=ttf_meta,
    )

    pairs = [
        ("hub_logret_1m", "vix_lag1m"),
        ("hub_logret_1m", "ngs_change_pct"),
        ("ttf_logret_1m", "ttf_hub_spread"),
        ("ttf_hub_spread", "ngs_deviation_pct"),
        ("hub_logret_1m", "ttf_logret_1m"),
    ]
    corrs, lags = analyze_pairs(features, pairs)

    # rolling corr hub vs ttf monthly returns
    roll = rolling_correlation(features["hub_logret_1m"], features["ttf_logret_1m"], window=24)
    roll_stats = {
        "mean": round(float(roll.mean()), 4),
        "std": round(float(roll.std()), 4),
        "min": round(float(roll.min()), 4),
        "max": round(float(roll.max()), 4),
    }

    # persist artifacts
    features_path = out_dir / "gas_features_monthly.csv"
    features.to_csv(features_path, float_format="%.6f")
    (out_dir / "gas_qa.json").write_text(json.dumps(qa_reports, indent=2), encoding="utf-8")
    (out_dir / "gas_correlations.json").write_text(json.dumps(corrs, indent=2), encoding="utf-8")
    (out_dir / "gas_leadlag.json").write_text(json.dumps(lags, indent=2), encoding="utf-8")

    report_lines = [
        "# Gas domain — pre-analysis report",
        "",
        f"Generated by `research/run_gas.py`",
        "",
        "## Data QA",
        "",
        _md_table(
            qa_reports,
            ["desk_id", "freq", "coverage_pct", "start", "end", "n_outliers_mad", "warnings"],
        ),
        "## Feature matrix",
        "",
        f"Monthly aligned rows: **{len(features.dropna(how='all'))}**",
        f"Output: `{features_path.relative_to(out_dir.parent.parent)}`",
        "",
        "## Hypothesis tests (literature-driven)",
        "",
        "### Correlations by sub-period",
        "",
        _md_table(corrs, ["period", "x", "y", "pearson_r", "p_value", "n"]),
        "### Lead-lag (monthly, max lag ±3)",
        "",
        _md_table(lags, ["period", "x", "y", "best_lag", "ccf_at_best"]),
        "",
        "### Rolling corr: HUB vs TTF monthly log-returns (24m window)",
        "",
        f"- mean: {roll_stats['mean']}",
        f"- std: {roll_stats['std']}",
        f"- range: [{roll_stats['min']}, {roll_stats['max']}]",
        "",
        "## Interpretation notes",
        "",
        "- **TTF** is FRED monthly USD proxy — not ICE TTF futures.",
        "- **NGS/CRU** via EIA public pages (`eia_public_inventories.py`); seasonal deviation is primary storage signal.",
        "- Sub-period `crisis_2022_plus` isolates EU gas regime per JAE 2024.",
        "- Next: add OVX, EU GIE storage %, then oil domain (`run_oil.py`).",
        "",
    ]

    report_path = out_dir / "gas_report.md"
    report_path.write_text("\n".join(report_lines), encoding="utf-8")

    print(f"QA: {len(qa_reports)} series")
    print(f"Features: {len(features)} monthly rows -> {features_path}")
    print(f"Correlations: {len(corrs)} tests")
    print(f"Report: {report_path}")
    if ngs_raw is None:
        print("NOTE: NGS missing — run scripts/desk_harvest/eia_public_inventories.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
