#!/usr/bin/env python3
"""Generate map_layers_wm.inc C table from wm_layer_sources.json (56 WM layers)."""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SRC = ROOT / "cache" / "ingest" / "wm_layer_sources.json"
OUT = ROOT / "src" / "map_layers_wm.inc"

# Desk already wires these
WIRED = {"ais", "waterways", "weather"}
# Linked KEYS id
KEY_FOR = {
    "ais": "ais",
    "liveTankers": "ais",
    "flights": "aviationstack",
    "fires": "firms",
    "ucdpEvents": "ucdp",
    "conflicts": "acled",
    "cyberThreats": "abuseipdb",
    "gpsJamming": "",
    "climate": "cdsapi",
}


def c_esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    doc = json.loads(SRC.read_text(encoding="utf-8"))
    keys = doc.get("keys") or []
    labels = doc.get("labels") or {}
    lines = ["/* auto-generated by gen_map_layers_wm.py — do not edit */", ""]
    # keep base desk layers first
    lines.append(
        '{ "coast", "Coastline base", "BASE",'
        '\n  "cache\\\\world_coast.csv", "",'
        '\n  "Equirectangular coast under AIS/MET", 1 },'
    )
    lines.append(
        '{ "weather", "MET heatmap TEMP/PRES/RH/WIND/CLD/PCP", "MET",'
        '\n  "", "",'
        '\n  "Open-Meteo (no key)", 1 },'
    )
    for k in keys:
        lab = labels.get(k, k)
        kid = KEY_FOR.get(k, "")
        wired = 1 if k in WIRED else 0
        kind = "LIVE" if k not in ("bases", "nuclear", "cables", "pipelines", "tradeRoutes") else "PLANNED"
        if k in ("ais", "waterways"):
            kind = "AIS"
        data = "cache\\\\live\\\\events.json" if kind in ("LIVE", "AIS") and k != "ais" else ""
        if k == "ais":
            data = "cache\\\\ais.key"
        if k == "waterways":
            data = "cache\\\\portwatch\\\\chokepoints.csv"
        note = f"World Monitor layer {k}"
        lines.append(
            f'{{ "{c_esc(k)}", "{c_esc(lab)}", "{kind}",\n'
            f'  "{data}", "{kid}",\n'
            f'  "{c_esc(note)}", {wired} }},'
        )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} layers={2+len(keys)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
