#!/usr/bin/env python3
"""Operational metadata for 30 reference projects — live/batch, map, refresh."""
from __future__ import annotations

# data_mode: live | mixed | batch | static | on_demand | library
# map_kind: globe | maritime | adsb | energy | chart | orderbook | workspace | graph | tui | none | library
# refresh_sec: typical minimum poll interval; None = on-demand / N/A

REFERENCE_OPS: dict[str, dict] = {
    "world_monitor": {
        "data_mode": "mixed",
        "needs_map": True,
        "map_kind": "globe",
        "refresh_sec": 60,
        "refresh_label": "API 30s–15min · RSS 15–60min · 56 layer map",
    },
    "globeops": {
        "data_mode": "mixed",
        "needs_map": True,
        "map_kind": "globe",
        "refresh_sec": 60,
        "refresh_label": "7 API live 30s–15min · 97 RSS · ASCII map",
    },
    "energy_monitor": {
        "data_mode": "mixed",
        "needs_map": True,
        "map_kind": "globe",
        "refresh_sec": 60,
        "refresh_label": "WM energy variant · AIS/commodity 1–15min",
    },
    "oriza": {
        "data_mode": "mixed",
        "needs_map": True,
        "map_kind": "workspace",
        "refresh_sec": 900,
        "refresh_label": "RSS 15min · scrape batch · weather demo",
    },
    "fincept_terminal": {
        "data_mode": "live",
        "needs_map": True,
        "map_kind": "workspace",
        "refresh_sec": 5,
        "refresh_label": "Streaming per connector (API keys)",
    },
    "typhoon_terminal": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "chart",
        "refresh_sec": 1,
        "refresh_label": "WebSocket tick · GPU charts",
    },
    "openbook": {
        "data_mode": "live",
        "needs_map": True,
        "map_kind": "orderbook",
        "refresh_sec": 1,
        "refresh_label": "Binance Futures WS @100ms depth",
    },
    "rs_trader": {
        "data_mode": "mixed",
        "needs_map": False,
        "map_kind": "workspace",
        "refresh_sec": 1,
        "refresh_label": "Live tick or CSV/Parquet replay",
    },
    "blackdesk": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "tui",
        "refresh_sec": 60,
        "refresh_label": "Yahoo poll · keyboard TUI",
    },
    "mkt": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "tui",
        "refresh_sec": 5,
        "refresh_label": "Coinbase WS · REST 1–5min · no API key",
    },
    "wickra_terminal": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "chart",
        "refresh_sec": 1,
        "refresh_label": "514 indicators stream · TUI or web",
    },
    "stockstui": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "tui",
        "refresh_sec": 60,
        "refresh_label": "yfinance + FRED poll",
    },
    "pftui": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "workspace",
        "refresh_sec": 300,
        "refresh_label": "19 sources · poll 5–60min · web dashboard",
    },
    "openterminalui": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "workspace",
        "refresh_sec": 60,
        "refresh_label": "Multi-chart shell · provider poll",
    },
    "triphopp_bloomberg": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "workspace",
        "refresh_sec": 60,
        "refresh_label": "FastAPI routers · macro/portfolio poll",
    },
    "feremabraz_bloomberg": {
        "data_mode": "static",
        "needs_map": False,
        "map_kind": "chart",
        "refresh_sec": None,
        "refresh_label": "Simulated data only · no live feed",
    },
    "openbb": {
        "data_mode": "mixed",
        "needs_map": False,
        "map_kind": "workspace",
        "refresh_sec": 300,
        "refresh_label": "Provider-dependent · EOD to intraday",
    },
    "egui_charts": {
        "data_mode": "library",
        "needs_map": False,
        "map_kind": "library",
        "refresh_sec": None,
        "refresh_label": "Host app defines data + refresh",
    },
    "obsyd": {
        "data_mode": "live",
        "needs_map": True,
        "map_kind": "energy",
        "refresh_sec": 3600,
        "refresh_label": "ENTSO-E hourly DA · GIE gas daily · flows",
    },
    "gridstatus": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "energy",
        "refresh_sec": 300,
        "refresh_label": "US ISO LMP/load · publish 5–60min",
    },
    "electricitymaps": {
        "data_mode": "live",
        "needs_map": True,
        "map_kind": "globe",
        "refresh_sec": 900,
        "refresh_label": "TSO parsers · carbon map 5–15min",
    },
    "herbie": {
        "data_mode": "batch",
        "needs_map": False,
        "map_kind": "none",
        "refresh_sec": None,
        "refresh_label": "NWP model cycles 1–6h · GRIB download",
    },
    "global_fishing_watch": {
        "data_mode": "batch",
        "needs_map": True,
        "map_kind": "maritime",
        "refresh_sec": 86400,
        "refresh_label": "AIS grid · ~5 day lag · 4Wings API",
    },
    "tar1090": {
        "data_mode": "live",
        "needs_map": True,
        "map_kind": "adsb",
        "refresh_sec": 2,
        "refresh_label": "readsb/dump1090 push · 1–2s tracks",
    },
    "opensanctions": {
        "data_mode": "batch",
        "needs_map": False,
        "map_kind": "none",
        "refresh_sec": 86400,
        "refresh_label": "Daily crawler · yente API on query",
    },
    "spiderfoot": {
        "data_mode": "on_demand",
        "needs_map": True,
        "map_kind": "graph",
        "refresh_sec": None,
        "refresh_label": "OSINT scan per target · 200+ modules",
    },
    "intelowl": {
        "data_mode": "on_demand",
        "needs_map": False,
        "map_kind": "workspace",
        "refresh_sec": None,
        "refresh_label": "Analyzer run per IOC submit",
    },
    "rotki": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "workspace",
        "refresh_sec": 300,
        "refresh_label": "Exchange/on-chain sync · ~5min",
    },
    "pysystemtrade": {
        "data_mode": "mixed",
        "needs_map": False,
        "map_kind": "chart",
        "refresh_sec": 86400,
        "refresh_label": "Daily futures bars · IB live optional",
    },
    "hummingbot": {
        "data_mode": "live",
        "needs_map": False,
        "map_kind": "none",
        "refresh_sec": 1,
        "refresh_label": "47 CEX/DEX connectors · WS order book",
    },
}
