"""AUTO-GENERATED by scripts/spine_codegen.py — do not edit."""
from __future__ import annotations
from dataclasses import dataclass


@dataclass(frozen=True)
class FredSeries:
    desk_id: str
    fred_id: str
    days: int = 1900


DESK_FRED: list[FredSeries] = [
    FredSeries("BE1", "T10YIE", 1900),
    FredSeries("BE5", "T5YIE", 1900),
    FredSeries("BRF", "DEXBZUS", 1900),
    FredSeries("BRT", "DCOILBRENTEU", 1900),
    FredSeries("CAD", "DEXCAUS", 1900),
    FredSeries("CNF", "DEXCHUS", 1900),
    FredSeries("COA", "PCOALAUUSDM", 1900),
    FredSeries("CPR", "PCOPPUSDM", 1900),
    FredSeries("DXY", "DTWEXBGS", 1900),
    FredSeries("E10", "IRLTLT01EZM156N", 3650),
    FredSeries("EDF", "ECBDFR", 3650),
    FredSeries("EUF", "DEXUSEU", 1900),
    FredSeries("FED", "DFF", 3650),
    FredSeries("GBF", "DEXUSUK", 1900),
    FredSeries("HOL", "DHOILNYH", 1900),
    FredSeries("HUB", "DHHNGSP", 1900),
    FredSeries("HYO", "BAMLH0A0HYM2", 1900),
    FredSeries("IGO", "BAMLC0A0CM", 1900),
    FredSeries("INF", "DEXINUS", 1900),
    FredSeries("JKM", "PNGASJPUSDM", 1900),
    FredSeries("JPF", "DEXJPUS", 1900),
    FredSeries("KEF", "DEXKOUS", 1900),
    FredSeries("MXF", "DEXMXUS", 1900),
    FredSeries("NAS", "NASDAQCOM", 1900),
    FredSeries("NOK", "DEXNOUS", 1900),
    FredSeries("NZF", "DEXUSNZ", 1900),
    FredSeries("RBO", "GASREGW", 1900),
    FredSeries("SEK", "DEXSDUS", 1900),
    FredSeries("SOF", "SOFR", 3650),
    FredSeries("SPX", "SP500", 1900),
    FredSeries("TTF", "PNGASEUUSDM", 1900),
    FredSeries("U10", "DGS10", 3650),
    FredSeries("U30", "DGS30", 3650),
    FredSeries("VIX", "VIXCLS", 1900),
    FredSeries("WTI", "DCOILWTICO", 1900),
    FredSeries("Z10", "IRLTLT01ZAM156N", 1900),
    FredSeries("ZAF", "DEXSFUS", 1900),
]
