"""FRED / desk series map for OPS DESK harvest (DATI_DA_SCARICARE.md)."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FredSeries:
    desk_id: str
    fred_id: str
    days: int = 1900  # ~5y daily


# Desk IDs -> flat cache/{desk_id}.csv (sources.c)
DESK_FRED: list[FredSeries] = [
    FredSeries("BRT", "DCOILBRENTEU"),
    FredSeries("WTI", "DCOILWTICO"),
    FredSeries("HUB", "DHHNGSP"),
    FredSeries("TTF", "PNGASEUUSDM"),
    FredSeries("COA", "PCOALAUUSDM"),
    FredSeries("JKM", "PNGASJPUSDM"),
    FredSeries("BRF", "DEXBZUS"),
    FredSeries("ZAF", "DEXSFUS"),
    FredSeries("INF", "DEXINUS"),
    FredSeries("CNF", "DEXCHUS"),
    FredSeries("MXF", "DEXMXUS"),
    FredSeries("KEF", "DEXKOUS"),
    FredSeries("EUF", "DEXUSEU"),
    FredSeries("NZF", "DEXUSNZ"),
    FredSeries("JPF", "DEXJPUS"),
    FredSeries("GBF", "DEXUSUK"),
    FredSeries("U10", "DGS10", 3650),
    FredSeries("E10", "IRLTLT01EZM156N", 3650),
    FredSeries("Z10", "IRLTLT01ZAM156N", 3650),
    FredSeries("SOF", "SOFR", 3650),
    FredSeries("EDF", "ECBDFR", 3650),
    FredSeries("CPR", "PCOPPUSDM"),
    FredSeries("BE5", "T5YIE", 3650),
    FredSeries("VIX", "VIXCLS"),
    FredSeries("CAD", "DEXCAUS"),
    FredSeries("DXY", "DTWEXBGS", 3650),
    FredSeries("NOK", "DEXNOUS", 3650),
    FredSeries("SEK", "DEXSDUS", 3650),
    FredSeries("U2", "DGS2", 3650),
    FredSeries("U5", "DGS5", 3650),
    FredSeries("BE1", "T10YIE", 3650),
    FredSeries("SPX", "SP500", 3650),
    FredSeries("HYO", "BAMLH0A0HYM2", 3650),
    FredSeries("IGO", "BAMLC0A0CM", 3650),
    FredSeries("NAS", "NASDAQCOM", 3650),
    FredSeries("FED", "DFF", 3650),
    FredSeries("U30", "DGS30", 3650),
    FredSeries("HOL", "DHOILNYH"),
    FredSeries("RBO", "GASREGW"),
    FredSeries("SPR", "WCSSTUS1", 2555),
    FredSeries("PROP", "DPROPANEMBTX", 2555),
    FredSeries("NGPR", "NGGPUS", 7300),
    FredSeries("NGCN", "NGCPUS", 7300),
    FredSeries("TP5", "DFII5", 3650),
    FredSeries("TP10", "DFII10", 3650),
    FredSeries("E3M", "IR3TIB01EZM156N", 3650),
    FredSeries("UNR", "UNRATE", 7300),
    FredSeries("CPI", "CPIAUCSL", 7300),
    FredSeries("TED", "TEDRATE", 3650),
    FredSeries("XAU", "GOLDAMGBD228NLBM", 3650),
]

# production.c — cache/{fred_id}.csv
PRODUCTION_FRED: list[tuple[str, int]] = [
    ("PCEPETUSDM", 7300),
    ("PCEPETCHNM", 7300),
    ("PCEPETDEUM", 7300),
    ("PCEPETJPNM", 7300),
    ("PCEPETINM", 7300),
    ("PCEPETBZZM", 7300),
    ("PCEPETGBRM", 7300),
    ("PCEPETFRAM", 7300),
    ("PCEPETITAM", 7300),
    ("PCEPETRUSM", 7300),
    ("PCEPETAUSM", 7300),
    ("PCEPETMEXM", 7300),
    ("PCEPETKORM", 7300),
    ("PCEPETZAFCM", 7300),
    ("PCEPETCANM", 7300),
    ("PCEPETESPM", 7300),
    ("PCEPETNLDM", 7300),
    ("PCEPETNORM", 7300),
    ("PCEPETPOLM", 7300),
    ("PCEPETTURM", 7300),
    ("SUNEPUS", 7300),
    ("WNDEPUS", 7300),
    ("HYDEPUS", 7300),
    ("NUCEPUS", 7300),
    ("NGNEPUS", 7300),
    ("CLEPUS", 7300),
    ("PETEPUS", 7300),
]

YAHOO_EQUITIES: list[tuple[str, str]] = [
    ("xom.us", "XOM"),
    ("cvx.us", "CVX"),
    ("shel.uk", "SHEL"),
    ("bp.uk", "BP"),
    ("tte.fr", "TTE"),
    ("eqnr.us", "EQNR"),
    ("eni.it", "ENI"),
    ("rep.mc", "REP"),
    ("cop.us", "COP"),
    ("eog.us", "EOG"),
    ("oxy.us", "OXY"),
    ("slb.us", "SLB"),
    ("hal.us", "HAL"),
    ("lng.us", "LNG"),
    ("vlo.us", "VLO"),
    ("mpc.us", "MPC"),
    ("enel.it", "ENEL"),
    ("ng.uk", "NG"),
    ("eon.de", "EON"),
    ("rwe.de", "RWE"),
    ("ibe.mc", "IBE"),
    ("nee.us", "NEE"),
    ("duk.us", "DUK"),
    ("engi.pa", "ENGI"),
    ("snam.it", "SNAM"),
    ("ig.it", "IG"),
    ("wmb.us", "WMB"),
    ("kmi.us", "KMI"),
    ("oke.us", "OKE"),
    ("edp.pt", "EDP"),
    ("orsted.co", "ORSTED"),
]

BINANCE_SYMBOLS: list[tuple[str, str]] = [
    ("BTCUSDT", "BTC"),
    ("ETHUSDT", "ETH"),
    ("PAXGUSDT", "XAU"),
]
