TRUNCATE legend_voce, legend_category CASCADE;
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('linee_elettriche', 'Linee elettriche', 'Power Lines', 'Power');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('lt_10kv', 'linee_elettriche', '< 10 kV', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('ge_10kv', 'linee_elettriche', '≥ 10 kV', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('ge_25kv', 'linee_elettriche', '≥ 25 kV', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('ge_52kv', 'linee_elettriche', '≥ 52 kV', 3);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('ge_132kv', 'linee_elettriche', '≥ 132 kV', 4);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('ge_220kv', 'linee_elettriche', '≥ 220 kV', 5);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('ge_310kv', 'linee_elettriche', '≥ 310 kV', 6);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('ge_550kv', 'linee_elettriche', '≥ 550 kV', 7);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('hvdc', 'linee_elettriche', 'HVDC', 8);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('trazione', 'linee_elettriche', 'Trazione (< 50 Hz)', 9);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('sotterranea', 'linee_elettriche', 'Sotterranea', 10);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('matricola_linea', 'linee_elettriche', 'Matricola linea', 11);
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('centrali_elettriche', 'Centrali elettriche', 'Power Plants', 'Power');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('carbone', 'centrali_elettriche', 'Carbone', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('geotermico', 'centrali_elettriche', 'Geotermico', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('idroelettrico', 'centrali_elettriche', 'Idroelettrico', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('nucleare', 'centrali_elettriche', 'Nucleare', 3);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('gas_petrolio', 'centrali_elettriche', 'Gas/Petrolio', 4);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('solare', 'centrali_elettriche', 'Solare', 5);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('eolico', 'centrali_elettriche', 'Eolico', 6);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('biomassa', 'centrali_elettriche', 'Biomassa', 7);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('termovalorizzatore', 'centrali_elettriche', 'Termovalorizzatore', 8);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('batterie', 'centrali_elettriche', 'Batterie', 9);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('other_unknown', 'centrali_elettriche', 'Other/Unknown', 10);
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('generatori', 'Generatori', 'Power Generators', 'Power');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('turbina_eolica', 'generatori', 'Turbina eolica', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('pannello_solare', 'generatori', 'Pannello solare', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('pannello_solare_nodo', 'generatori', 'Pannello solare (nodo)', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('generatore_altro', 'generatori', 'Generatore (altro)', 3);
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('supporti_linee', 'Supporti per linee elettriche', 'Power Line Supports', 'Power');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('torre_traliccio', 'supporti_linee', 'Torre/traliccio', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('traliccio_transizione', 'supporti_linee', 'Traliccio di transizione', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('palo_elettrico', 'supporti_linee', 'Palo elettrico', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('palo_transizione', 'supporti_linee', 'Palo di transizione', 3);
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('apparecchiature_manovra', 'Apparecchiature di manovra', 'Switchgear', 'Power');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('trasformatore', 'apparecchiature_manovra', 'Trasformatore', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('trasformatore_3', 'apparecchiature_manovra', 'Trasformatore a 3 avvolgimenti', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('current_transformer', 'apparecchiature_manovra', 'Current transformer', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('potential_transformer', 'apparecchiature_manovra', 'Potential transformer', 3);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('sezionatore', 'apparecchiature_manovra', 'Sezionatore', 4);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('interruttore', 'apparecchiature_manovra', 'Interruttore', 5);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('organo_manovra_generico', 'apparecchiature_manovra', 'Organo di manovra (generico)', 6);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('reattanza_serie', 'apparecchiature_manovra', 'Reattanza serie', 7);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('reattanza_shunt', 'apparecchiature_manovra', 'Reattanza shunt', 8);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('condensatore_serie', 'apparecchiature_manovra', 'Condensatore serie', 9);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('condensatore_shunt', 'apparecchiature_manovra', 'Condensatore shunt', 10);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('filtro', 'apparecchiature_manovra', 'Filtro', 11);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('compensatore_altro', 'apparecchiature_manovra', 'Compensatore (altro)', 12);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('conversione_dc', 'apparecchiature_manovra', 'Sottostazione di conversione DC', 13);
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('telecomunicazioni', 'Telecomunicazioni', 'Telecoms', 'Telecoms');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('cavo', 'telecomunicazioni', 'Cavo', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('torre_palo_telecom', 'telecomunicazioni', 'Torre/palo', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('datacenter', 'telecomunicazioni', 'Datacenter', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('centrale_telefonica', 'telecomunicazioni', 'Centrale telefonica', 3);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('armadio', 'telecomunicazioni', 'Armadio', 4);
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('gas', 'Gas', 'Gas', 'Oil & Natural Gas');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('gas_tx_dn700', 'gas', 'Transmission >= DN 700', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('gas_tx_dn300', 'gas', 'Transmission >= DN 300', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('gas_tx_lt_dn300', 'gas', 'Transmission < DN 300', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('gas_dist_high', 'gas', 'Distribution High Pressure', 3);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('gas_dist_intermediate', 'gas', 'Distribution Intermediate Pressure', 4);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('gas_dist_low', 'gas', 'Distribution Low Pressure', 5);
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('petrolio', 'Petrolio', 'Petroleum', 'Oil & Natural Gas');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('petrolio_oil', 'petrolio', 'Petrolio', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('prodotti_intermedi', 'petrolio', 'Prodotti intermedi del petrolio', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('carburante', 'petrolio', 'Carburante', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('idrogeno', 'petrolio', 'Idrogeno', 3);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('infrastrutture_petrolifere', 'petrolio', 'Infrastrutture petrolifere', 4);
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('acqua', 'Acqua', 'Water', 'Water');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('acqua_dolce', 'acqua', 'Acqua dolce', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('acqua_calda', 'acqua', 'Acqua calda', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('vapore', 'acqua', 'Vapore', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('acque_reflue', 'acqua', 'Acque reflue', 3);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('impianto_trattamento_acque', 'acqua', 'Impianto trattamento acque', 4);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('stazione_pompaggio_acque', 'acqua', 'Stazione pompaggio acque', 5);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('impianto_depurazione', 'acqua', 'Impianto di depurazione', 6);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('stazione_pompaggio_reflui', 'acqua', 'Stazione pompaggio reflui', 7);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('stazione_pompaggio_altro', 'acqua', 'Stazione di pompaggio (altro)', 8);
INSERT INTO legend_category(id, label_it, label_en, layer_oim) VALUES ('other_pipelines', 'Other Pipelines', 'Other Pipelines', 'Other Pipelines');
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('oxygen', 'other_pipelines', 'Oxygen', 0);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('co2', 'other_pipelines', 'CO2', 1);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('nitrogen', 'other_pipelines', 'Nitrogen', 2);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('beer', 'other_pipelines', 'Beer', 3);
INSERT INTO legend_voce(id, category_id, label_it, sort_order) VALUES ('altro_pipeline', 'other_pipelines', 'Altro', 4);
DO $$ BEGIN ASSERT (SELECT count(*) FROM legend_category) = 10, 'expected 10 categories'; ASSERT (SELECT count(*) FROM legend_voce) = 75, 'expected 75 voci'; END $$;
SELECT 'legend ok' AS status, (SELECT count(*) FROM legend_category) AS categories, (SELECT count(*) FROM legend_voce) AS voci;
