#!/usr/bin/env python3
"""Generate unified catalog + FRED harvest list from desk spine manifest."""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPINE = ROOT / "config" / "desk_spine.json"
FX = ROOT / "config" / "fx_manifest.json"
SOURCES_C = ROOT / "src" / "sources.c"
OUT_DIR = ROOT / "config" / "generated"
HARVEST_OUT = ROOT / "scripts" / "desk_harvest" / "series_config_generated.py"

FRED_RE = re.compile(
    r'\{\s*"([A-Z0-9]{3})"\s*,\s*"([A-Z0-9_]+)"\s*,\s*NULL\s*,\s*L"[^"]*"\s*,\s*SER_\w+\s*,\s*SRC_FRED'
)


def parse_sources_c() -> dict[str, str]:
    text = SOURCES_C.read_text(encoding="utf-8")
    return {m.group(1): m.group(2) for m in FRED_RE.finditer(text)}


def main() -> int:
    if not SPINE.is_file():
        print(f"FAIL missing {SPINE}")
        return 1

    spine = json.loads(SPINE.read_text(encoding="utf-8"))
    fx = json.loads(FX.read_text(encoding="utf-8")) if FX.is_file() else {"pairs": []}
    fred_map = parse_sources_c()

    series_rows = []
    for s in spine.get("series", []):
        sid = s["id"]
        row = dict(s)
        if sid in fred_map:
            row["fred_id"] = fred_map[sid]
        series_rows.append(row)

    fred_list = []
    seen: set[str] = set()
    for desk_id, fred_id in sorted(fred_map.items()):
        if desk_id in seen:
            continue
        seen.add(desk_id)
        days = 3650 if desk_id in ("U10", "U2", "U5", "U30", "SOF", "EDF", "E10", "FED") else 1900
        fred_list.append({"desk_id": desk_id, "fred_id": fred_id, "days": days})

    catalog = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "spine_version": spine.get("version"),
        "series": series_rows,
        "pipelines": spine.get("pipelines", []),
        "fx_pairs": fx.get("pairs", []),
        "fx_hub": fx.get("hub", "EUR"),
        "fred_sources_count": len(fred_map),
    }

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "catalog.json").write_text(json.dumps(catalog, indent=2), encoding="utf-8")
    (OUT_DIR / "series_fred.json").write_text(json.dumps(fred_list, indent=2), encoding="utf-8")

    lines = [
        '"""AUTO-GENERATED by scripts/spine_codegen.py — do not edit."""',
        "from __future__ import annotations",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class FredSeries:",
        "    desk_id: str",
        "    fred_id: str",
        "    days: int = 1900",
        "",
        "",
        "DESK_FRED: list[FredSeries] = [",
    ]
    for item in fred_list:
        lines.append(
            f'    FredSeries("{item["desk_id"]}", "{item["fred_id"]}", {item["days"]}),'
        )
    lines.append("]")
    lines.append("")

    HARVEST_OUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"OK catalog -> {OUT_DIR / 'catalog.json'}  ({len(series_rows)} spine series)")
    print(f"OK fred list -> {OUT_DIR / 'series_fred.json'}  ({len(fred_list)} fred)")
    print(f"OK harvest -> {HARVEST_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
